# Configurações de Identidade
owner: FiscoSuper
repo: status

# Sites para Monitoramento
sites:
  - name: Site FiscoSuper
    url: https://fiscosuper.com.br/
  - name: App FiscoSuper
    url: https://apps.fiscosuper.com.br/login.xhtml
  - name: Api FiscoSuper
    url: https://apps.fiscosuper.com.br/swagger/

# Configuração da Página de Status
status-website:
  # O cname deve ser exatamente o que você configurou no seu DNS
  cname: status.fiscosuper.com.br
  
  # Como você usa CNAME, o baseUrl deve permanecer comentado
  # baseUrl: /status

  # Personalização Visual e Textual
  logoUrl: https://fiscosuper.com.br/favicon.ico
  name: Status FiscoSuper
  introTitle: "**Monitoramento de Disponibilidade FiscoSuper**"
  introMessage: "Esta página apresenta o status em tempo real dos nossos serviços e aplicações. Monitoramento automático via GitHub Actions."
  
  navbar:
    - title: Status
      href: /
    # - title: GitHub
    #   href: https://github.com/$OWNER/$REPO

# Configurações Adicionais (Opcional)
# commitMessages:
#   readmeContent: ":pencil: Update status summary [skip ci]"
#   statsUpdate: ":chart_with_upwards_trend: Update uptime stats [skip ci]"
